strawberry-py/strawberry-py

- pie/i18n/__init__.py
Same situation as with strawberry-tools.
Already discussed before forking at https://github.com/pumpkin-py/pumpkin-py/pull/338
> I18n inter

- .github/workflows/build-image.yml
The build is not running on build update and also can't be triggered manually. This fixes the problem
> [Build] Fix build not running

- Dockerfile
The problem with these changes is that the "myuser" user does not have permissions to do things like timezone change or tempdir creation...
> [Docker] Revert changes by Czechbol

- Dockerfile
> [Docker] Fix git safe directory problem

- Dockerfile
I've missed a backslash at the end of line.
> [Docker] Fix missing symbol

- README.md
Badges were not working as there were wrong addresses. Same goes for the link to the docs.
> [README] Fix badges

- docs/_snippets/_apt_dependencies.rst
- docs/development/code_quality.rst
- docs/development/developing_modules.rst
- docs/development/imports.rst
- docs/development/installation.rst
- docs/development/repository.rst
- docs/general/index.rst
- docs/production/containers.rst
- docs/production/direct.rst
The docs are bit messy, some of the information is not actual and it's a bit chaotic.
The rework is needed to get it to some level, when people can easily spin their own instance of the bot and get an environment for development.
> Rework of Docs

- .github/workflows/docker-test.yml
- .pre-commit-config.yaml
- Dockerfile
Add build tests for dockerfile. docker-compose and the same for pre-commit
> Docker tests

- pie/po/cs.popie
- pie/po/sk.popie
- pie/utils/time.py
Based on requests from users, this might help us easily explain what is the supported format of date/time.
> [Time] Time format example helper function

- pie/utils/discord.py
This function will be used in reminder and probably also the sudo commands.
> [Discord utils] Add split message url function

- .github/workflows/build.yml
- .pre-commit-config.yaml
- requirements-dev.txt
> Python 3.12 tests

- pie/utils/objects.py
ConfirmView was working with classic commands only. The slash commands support is needed not just for future use, but for the Reminder module rework as well.
> [ConfirmView] Add support for AppCommands

- requirements.txt
This might need a bit of testing before we can put it publicly.
> Upgrade SQLAlchemy to 2.0+

- .github/dependabot.yml
Let's use dependabot to at least notify us when update is needed.
> [Dependabot] Auto updates

- pie/bot.py
Fixes this issue:
```
ERROR arcascz (140547421733126145) #log Testovací server: ModuleNotFoundError: No module named 'modules.fun.karma'
Traceback (most recent call last):
File "/root/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
ret = await coro(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/strawberry-py/modules/base/admin/module.py", line 395, in module_load
await self.bot.load_extension("modules." + name + ".module")
File "/root/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1009, in load_extension
spec = importlib.util.find_spec(name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib.util>", line 94, in find_spec
ModuleNotFoundError: No module named 'modules.fun.karma'
```
There should be a ExtensionNotFound …
> [Bot] Improve extension loading

- modules/base/errors/module.py
Mistakes were made during the rework of Error module. This should correct the two worst - code duplication and bad handling of original errors.
> Fix errors

- .github/workflows/docker-test.yml
- docker-compose.yml
- entrypoint.sh
- modules/base/admin/module.py
- pie/bot.py
- strawberry.py
This PR let's the bot gracefuly shutdown / restart when:
- using !strawberry shutdown
- using !strawberry restart
- receiving SIGKILL / SIGTERM (docker container stop, CTRL+C, ...)
> Graceful shutdown / restart / interupt

- modules/base/admin/module.py
- modules/base/po/cs.popie
- modules/base/po/sk.popie
- pie/repository/__init__.py
- add missing typing to Admin module
- optimize the response time by running the repo functions that manipulate with GIT using run_in_executor
- add automatic update checking and notifying
- add version info to repo list command
> [Admin] Improve repo handling

- modules/base/admin/module.py
- modules/base/po/cs.popie
- modules/base/po/sk.popie
This improves the information for admin about what's updating
> [Admin] Improve update info

- modules/base/admin/module.py
Improve the info about outdated repositories.
> [Admin] Improve update check info

- modules/base/admin/module.py
It's better to have this as debug instead of info.
> [Admin] Decrease update log level

- modules/base/admin/module.py
- pie/repository/__init__.py
- strawberry.py
- added stack trace print in entry file to catch and print all errors
- use property for repo and branch name representation in Repository
- show branch name in repo list
> [Admin] Add repository branch info

- modules/base/acl/module.py
- add typing 
- refactor variable names 
- changed List to list 
first partial fix for #89
> {acl} Added typing + refactor

- modules/base/acl/module.py
Address issue #91 
logging is async function and it can't be easily called in normall function, so I think it is not worth it.
> [ACL] Change obj -> overwrite and add typing

- pie/acl/__init__.py
- pie/check.py
This fixes a critical error in ACL2 - it was not working correctly with app commands.
> [ACL] Split ACL check

- pie/acl/__init__.py
Fixes behavior for app_commands as those does not handle exceptions well.
> [ACL] Fix ACL behavior for app_commands

- modules/base/profiler/module.py
In the PR for the Profiler I've forgot to rever the app_acl changes back to acl2 as the bug in the ACL was already fixed and the app_acl removed.
> [Profiler] Fix profiler ACL checks

- README.md
User documentation was moved 
https://github.com/strawberry-py/strawberry-docs/pull/4
> user documentation moved to ReadTheDocs

- pie/utils/text.py
forgot spoiler mark in smart split
> added spoiler mark
